# Generated by Django 4.0.4 on 2022-04-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_kitoblar_janr'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitoblar',
            name='size',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
