# Generated by Django 4.0.4 on 2022-04-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0001_initial'),
        ('books', '0003_kitoblar_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitoblar',
            name='janr',
            field=models.CharField(choices=[('Ilmiy', 'Ilmiy'), ('Badiiy', 'Badiiy '), ('Fantastik', 'Fantastik'), ('Tarixiy-adabiy', 'Tarixiy-adabiy'), ('Tarixiy', 'Tarixiy'), ('Detektiv', 'Detektiv'), ('Avtobiografik', 'Avtobiografik'), ('Boshqa', 'Boshqa')], default='Boshqa', max_length=400),
        ),
        migrations.AlterField(
            model_name='kitoblar',
            name='user',
            field=models.ForeignKey(default='Kitobxon', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='books', to='readers.kitobxon'),
        ),
    ]
