# Generated by Django 4.0.4 on 2022-04-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_kitoblar_janr_alter_kitoblar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kategoriyaga nom bering...', max_length=5000)),
            ],
            options={
                'verbose_name': 'Kategoriyalar ',
            },
        ),
        migrations.RemoveField(
            model_name='kitoblar',
            name='janr',
        ),
        migrations.AddField(
            model_name='kitoblar',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kitoblar', to='books.category'),
        ),
    ]
